### ISSUE TITLE
Syntax coloring gets confused by quotes

### ISSUE THREAD

**Issue by randallsquared** [haad/vs-language-ansible#3]
Moderately complex use of quotes or templates causes everything after to get colored as a string.

For example:

```

---
- hosts: provision-pool
  tasks:
    - name: "figure-out default gateway"
      shell: /sbin/route -n | grep -v " 0.0.0.0" | grep "eth0" | awk '{print $2}' | head -n 1
      register: network_gateway_ip
```

![screen shot 2016-09-12 at 3 35 24 pm](https://cloud.githubusercontent.com/assets/1184539/18450107/a4491ee8-78ff-11e6-8ec4-afc4f3a1c1e4.png)

I'm using VS Code 1.5.2 and v0.2.3.

(Actually, uninstalling the plugin doesn't seem to change anything, which makes me wonder if it's just somehow disabled?)
